"""
PDF report generator using ReportLab.
"""
from pathlib import Path
from typing import Any

import structlog
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.db.models import Insight, Query

logger = structlog.get_logger(__name__)


class PDFGenerator:
    """Generates professional PDF reports from query results and insights."""

    async def generate(
        self,
        report_id: int,
        title: str,
        description: str | None,
        queries: list[Query],
        output_dir: str,
        insights: list[Insight] | None = None,
    ) -> str:
        """Build the PDF and return its file path."""
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        output_path = str(Path(output_dir) / f"report_{report_id}.pdf")

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        story = self._build_story(title, description, queries, insights or [])
        doc.build(story)

        logger.info("PDF generated", path=output_path, report_id=report_id)
        return output_path

    def _build_story(
        self,
        title: str,
        description: str | None,
        queries: list[Query],
        insights: list[Insight],
    ) -> list:
        styles = getSampleStyleSheet()
        story = []

        # ── Title ─────────────────────────────────────────────────
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=22,
            spaceAfter=6,
        )
        story.append(Paragraph(title, title_style))

        if description:
            story.append(Paragraph(description, styles["Normal"]))
        story.append(Spacer(1, 6 * mm))

        # ── Insights section ─────────────────────────────────────
        if insights:
            story.append(Paragraph("AI Insights", styles["Heading1"]))
            story.append(Spacer(1, 2 * mm))

            severity_colors = {
                "critical": colors.HexColor("#dc2626"),
                "high": colors.HexColor("#ea580c"),
                "medium": colors.HexColor("#ca8a04"),
                "low": colors.HexColor("#65a30d"),
            }
            for insight in insights:
                badge_style = ParagraphStyle(
                    "InsightSeverity",
                    parent=styles["Normal"],
                    fontSize=8,
                    textColor=severity_colors.get(insight.severity, colors.grey),
                )
                story.append(Paragraph(insight.severity.upper(), badge_style))
                story.append(Paragraph(insight.title, styles["Heading3"]))
                story.append(Paragraph(insight.description, styles["Normal"]))
                story.append(Spacer(1, 4 * mm))

            story.append(Spacer(1, 4 * mm))

        # ── Query sections ────────────────────────────────────────
        for i, query in enumerate(queries, start=1):
            story.append(Paragraph(f"Query {i}: {query.question}", styles["Heading2"]))
            story.append(Spacer(1, 2 * mm))

            if query.generated_sql:
                code_style = ParagraphStyle(
                    "Code", parent=styles["Code"], fontSize=8, leading=12
                )
                story.append(Paragraph(f"<b>SQL:</b> {query.generated_sql}", code_style))
                story.append(Spacer(1, 2 * mm))

            if query.results:
                table_data = self._results_to_table(query.results)
                if table_data:
                    t = Table(table_data, repeatRows=1)
                    t.setStyle(self._table_style())
                    story.append(t)

            story.append(Spacer(1, 8 * mm))

        # ── Footer ────────────────────────────────────────────────
        footer_style = ParagraphStyle(
            "Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey
        )
        story.append(Spacer(1, 10 * mm))
        story.append(Paragraph("Generated by AI BI Dashboard", footer_style))

        return story

    @staticmethod
    def _results_to_table(results: list[dict[str, Any]]) -> list[list[str]]:
        if not results:
            return []
        headers = list(results[0].keys())
        rows = [[str(row.get(h, "")) for h in headers] for row in results[:50]]
        return [headers] + rows

    @staticmethod
    def _table_style() -> TableStyle:
        return TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3b82d4")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f8fa")]),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ])
